Configuration/14 setup templates for new issues
qwik-resume/qwik-resume pull request #16
Opened 2023-07-18 17:24 UTC by cstroliadavis

# Issue:

#14 [CONFIGURATION] Setup template for new issues

# What this does:

This sets up some new issue templates for creating issues for qwik resume.

2023-07-21 22:19 UTC, Tekner commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - Device: [e.g. iPhone6] (if a phone and known, otherwise delete this line)
I don't think this should only be applicable "if a phone and known"
I believe device could be used to differentiate between Desktop & Mobile for the same browser, which is asked below
I think we could also benefit from asking for the device orientation if a screenshot isn't provided. Tablets and some large phones could render in mobile or desktop (based on min-width media queries) and without a screenshot, we might not know which styles to look at (if applicable).

2023-07-21 22:21 UTC, Tekner commented on .github/ISSUE_TEMPLATE/configuration_update.md
> +A clear and concise description of what the problem is in user story format. Ex. As a user, it would be helpful to ...
This is a very nitpicky thing, but if we're to be consistent, should we use "e.g." or "Ex."?
You use "Ex." here and in feature_request.md, but you used "e.g." in bug_report.md

2023-07-21 22:22 UTC, Tekner requested changes
It looks good, but I'd like to request we not include language limiting the Bug Report's Device info to "if phone and known"

2023-07-23 16:18 UTC, cstroliadavis commented on .github/ISSUE_TEMPLATE/configuration_update.md
> +A clear and concise description of what the problem is in user story format. Ex. As a user, it would be helpful to ...
lol. I think I used some of the boilerplate stuff for this and just modified it, so that's probably why there is some inconsistency, but good catch. I'll see about fixing it.

2023-07-25 14:42 UTC, Tekner approved these changes

2023-08-02 18:35 UTC, merged